DSO Update after 15 years - Star clusters
CelestiaProject/CelestiaContent pull request #108
Opened 2023-06-08 21:57 UTC by GurrenLagannTSS

2023-06-09 06:20 UTC, 375gnu requested changes
1) Please provide meaningful names for commints and PR, e.g. "Update globular and open cluster catalog"
2) Updated globulars lost their names present in the original catalog.

2023-06-09 23:01 UTC, GurrenLagannTSS commented
Gitmerged the commit fixing the missing IDs with the older one to make a more appropriate commit name, using what you suggested. Anything else that needs fixing?

2023-08-06 11:57 UTC, ajtribick approved these changes

2023-08-06 16:08 UTC, 375gnu approved these changes

2023-08-07 06:11 UTC, merged