Add licensing information to source code files and translations
CelestiaProject/CelestiaContent pull request #143
Opened 2023-12-28 20:07 UTC by ajtribick

Most source code files appear to be under GPL-2.0-or-later, so use that as the identifier.
Translation copyright information is derived from Git history and may have errors.
Copyright information for the debian directory taken from debian/copyright

2023-12-29 09:42 UTC, 375gnu commented
I believe *.po changes will be lost on update from transifex.

2023-12-29 17:37 UTC, ajtribick commented
The [documentation](https://help.transifex.com/en/articles/6220794-gettext-po) does mention that comments are supported but I'm not sure whether or not that also applies to the file header. My instinct here is to add them to the .po files and then do a test update with Transifex, if that results in erased headers then we can move the information to the dep5 file.

The other issue is that the current .pot extract process would remove the comments from celestia-data.pot - I would in any case like to update the generation process similar to the changes in the Celestia repository to make it possible to run the update on Windows, so would address that when I do this.

2023-12-29 17:45 UTC, Askaniy commented
I'm in the process of translating on Transifex. Please write, I need to wait for this commit to be merged or vice versa, not to wait

2024-01-07 10:07 UTC, 375gnu requested changes
please remove po files, their changes will be lost on the next update from transifex

2024-01-07 10:40 UTC, ajtribick commented
Did you test that?

2024-01-07 11:02 UTC, 375gnu commented
Let's make a small PR to update *.pot file only and see if comments are updated in *.po files too.

2024-01-07 11:18 UTC, ajtribick commented
Ok. I did a minor change to the German translation (which has some custom comments in the header already), I guess there's a way to trigger a Transifex PR somehow?

2024-01-07 12:18 UTC, 375gnu commented
You can download the po file, that's how it looks now:
```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Celestia Development Team
# This file is distributed under the same license as the celestia package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Hleb Valoshka <375gnu@gmail.com>, 2023
# Andrew Tribick, 2024
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: celestia 1.7.0\n"
"Report-Msgid-Bugs-To: team@celestiaproject.space\n"
"POT-Creation-Date: 2023-07-27 10:41+0300\n"
"PO-Revision-Date: 2023-11-03 11:00+0000\n"
"Last-Translator: Andrew Tribick, 2024\n"
"Language-Team: German (https://app.transifex.com/celestia/teams/93131/de/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

```

2024-01-07 12:22 UTC, 375gnu commented
I've updated celeatia-data.pot manually, now belarusian po looks as
```
# SPDX-FileCopyrightText: Celestia Development team
# SPDX-License-Identifier: GPL-2.0-or-later
# 
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Celestia Development Team
# This file is distributed under the same license as the celestia package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Hleb Valoshka <375gnu@gmail.com>, 2024
```
So everything is good.

2024-01-07 12:22 UTC, 375gnu approved these changes

2024-01-07 14:52 UTC, ajtribick commented
Ok, then I think we can put the copyright text as "Celestia Development Team, Translators" so that gets replicated into the files?

2024-01-09 18:17 UTC, ajtribick commented
Updated and replicated to .po files.

2024-01-10 17:39 UTC, merged